# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from PyQt5.QtCore import QSettings

import settings
import spider_thread

class Ui_MainWindow(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, mainwidget):
        mainwidget.setObjectName("mainwidget")
        mainwidget.resize(343, 427)
        self.gridLayout = QtWidgets.QGridLayout(mainwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textEditInfo = QtWidgets.QTextEdit(mainwidget)
        self.textEditInfo.setObjectName("textEditInfo")
        self.gridLayout.addWidget(self.textEditInfo, 1, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(mainwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(mainwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txtWord = QtWidgets.QLineEdit(mainwidget)
        self.txtWord.setObjectName("txtWord")
        self.horizontalLayout.addWidget(self.txtWord)
        self.btnConfirm = QtWidgets.QPushButton(mainwidget)
        self.btnConfirm.setObjectName("btnConfirm")
        self.horizontalLayout.addWidget(self.btnConfirm)
        self.btnCancel = QtWidgets.QPushButton(mainwidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSettings = QtWidgets.QPushButton(mainwidget)
        self.btnSettings.setObjectName("btnSettings")
        self.horizontalLayout_2.addWidget(self.btnSettings)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(mainwidget)
        QtCore.QMetaObject.connectSlotsByName(mainwidget)

        self.instance = mainwidget

        self.initData()
        self.initTextView()

    def retranslateUi(self, mainwidget):
        _translate = QtCore.QCoreApplication.translate
        mainwidget.setWindowTitle(_translate("mainwidget", "wallhaven爬虫"))
        self.label.setText(_translate("mainwidget", "搜索关键字"))
        self.btnConfirm.setText(_translate("mainwidget", "开始"))
        self.btnCancel.setText(_translate("mainwidget", "停止"))
        self.btnSettings.setText(_translate("mainwidget", "设置"))


    def initData(self):
        self.btnConfirm.clicked.connect(self.startSpider)
        self.btnCancel.clicked.connect(self.stopSpider)
        self.textEditInfo.textChanged.connect(self.scrollToEnd)
        self.textEditInfo.setReadOnly(True)
        self.txtWord.setFocus()
        self.btnCancel.setEnabled(False)
        self.btnSettings.clicked.connect(self.openSettingsDialog)
        self.textEditInfo.document().setMaximumBlockCount(100) # 设置最大行数

        set = QSettings('config.ini',QSettings.IniFormat)
        self.downloadDir = set.value('path', './download')

    def initTextView(self):
        self.textEditInfo.append('\n\n\n请输入搜索关键词后，点击开始下载')
        self.textEditInfo.append('输入toplist下载热门榜单内容')
        self.textEditInfo.append('仅支持英文关键词\n\n\n')

    def openSettingsDialog(self):
        Settings = QDialog(self.instance)
        ui = settings.Ui_settings()
        ui.setupUi(Settings)
        ui.initData()
        Settings.exec()
        self.downloadDir = ui.path


    def addText(self, str):
        self.textEditInfo.append(str)

    def updateProgress(self, val):
        self.progressBar.setValue(int(val))

    def clearText(self):
        self.textEditInfo.clear()


    def scrollToEnd(self):
        self.textEditInfo.moveCursor(QtGui.QTextCursor.MoveOperation.End)

    def startSpider(self):
        word = self.txtWord.text()
        if len(word) == 0:
            self.addText('关键词为空')
            return
        self.updateProgress(0)
        self.btnConfirm.setEnabled(False)
        self.btnCancel.setEnabled(True)
        self.sp = spider_thread.Spider()
        self.sp.set_message(self.addText)
        self.sp.set_progress(self.updateProgress)
        self.sp.set_finish(self.restartView)
        self.sp.set_word(word)
        self.sp.set_download_path(self.downloadDir)
        self.sp.start()

    def stopSpider(self):
        self.sp.exit = True
        self.restartView()

    def restartView(self):
        self.updateProgress(0)
        self.btnConfirm.setEnabled(True)
        self.btnCancel.setEnabled(False)
        self.initTextView()

