# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from PyQt5.QtCore import QSettings

import os


class Ui_settings(QtWidgets.QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.path = ''

    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(337, 303)
        self.verticalLayout = QtWidgets.QVBoxLayout(settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(settings)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtPath = QtWidgets.QLineEdit(self.groupBox)
        self.txtPath.setObjectName("txtPath")
        self.horizontalLayout.addWidget(self.txtPath)
        self.btnChoose = QtWidgets.QPushButton(self.groupBox)
        self.btnChoose.setObjectName("btnChoose")
        self.horizontalLayout.addWidget(self.btnChoose)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(settings)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(settings)
        QtCore.QMetaObject.connectSlotsByName(settings)

        self.btnChoose.clicked.connect(self.choosePath)
        self.buttonBox.accepted.connect(self.finish)
        self.buttonBox.rejected.connect(self.cancel)

        self.instance = settings

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "设置"))
        self.groupBox.setTitle(_translate("settings", "路径"))
        self.btnChoose.setText(_translate("settings", "选择"))

    def initData(self):
        set = QSettings('config.ini',QSettings.IniFormat)
        self.path = set.value('path', './download')

        self.txtPath.setText(self.path)

    def choosePath(self):
        pa = QFileDialog.getExistingDirectory(self.instance, '选择', self.txtPath.text())
        if len(pa) > 0:
            self.txtPath.setText(pa)

    def saveData(self):
        set = QSettings('config.ini',QSettings.IniFormat)
        set.setValue('path', self.path)

    def finish(self):
        if not os.path.exists(self.txtPath.text()):
            QMessageBox.critical(self.instance, '错误', '当前路径不存在')
            return
        self.path = self.txtPath.text()
        if self.path.endswith('/'):
            self.path = self.path[: len(self.path)-1]
        self.saveData()
        self.instance.accept()

    def cancel(self):
        self.saveData()
        self.instance.reject()